# Generated by Django 3.0.11 on 2021-01-13 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apicall',
            old_name='callled_at',
            new_name='called_at',
        ),
    ]
