# Generated by Django 3.0.11 on 2021-01-13 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0002_auto_20210113_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='apicall',
            name='api_name',
            field=models.CharField(default='', max_length=20),
        ),
    ]
